### ISSUE TITLE
P1SIDED or PONESIDED

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#27]
### Plugin Name with version

"@progidev/jss-formulas-statistics": "2.1.0"

### JSpreadsheet version

v9.x

### Describe the bug

Hi @GBonnaire 

So I'm logging `jspreadsheet.formulaDoc` and I'm seeing entries like `TTEST.ONESAMPLE.P1SIDED()`, `TTEST.ONESAMPLE.P2SIDED()`, etc. But when I'm typing in those names, autocomplete thingy suggests:

<img width="288" alt="image" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/2717746/41b01bf7-236d-4c71-b0e0-34ffd7249979">

And formulas don't seem to work.
I guess a bug?

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Hi,

Fixed on 2.1.1

TTEST.ONESAMPLE.P1SIDED AND TTEST.ONESAMPLE.P2SIDED

**Comment by dmt0** [comment]
Hey @GBonnaire seems like there are more problematic formulas there:

Documentation doesn't show up:
TTEST.ONESAMPLES.P1SIDED
TTEST.ONESAMPLES.P2SIDED
TTEST.TWOSAMPLES.P1SIDED
TTEST.TWOSAMPLES.P2SIDED
MANNWUTEST.P1TAILED
MANNWUTEST.P2TAILED 
BARNARDSTEST.P1TAILED

Calculation doesn't work: 
BARNARDSTEST.P2TAILED

**Comment by GBonnaire** [comment]
Oh yes, i have check all formulas and now it's ok on v2.1.2

Many thanks

**Comment by dmt0** [comment]
Hey, still more issues.

Documentation for:
BARNARDSTEST.P1TAILED
BARNARDSTEST.P2TAILED
MANNWUTEST.P1TAILED
MANNWUTEST.P2TAILED
TTEST.ONESAMPLE.P1SIDED
TTEST.ONESAMPLE.P2SIDED
TTEST.TWOSAMPLES.P1SIDED
TTEST.TWOSAMPLES.P2SIDED

still doesn't show up

**Comment by GBonnaire** [comment]
Can you clear cache ? for me it's work this functions

**Comment by dmt0** [comment]
Not a cache problem, I have webpack in watch mode. Just to clarify:
<img width="420" alt="image" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/2717746/ace07879-abf8-41a5-8aa8-fe8ab1c0669c">
When I click that popup, I don't get docs for those listed functions, but get them for all the others.
I'm on "@progidev/jss-formulas-statistics": "2.1.2"

**Comment by GBonnaire** [comment]
<img width="576" alt="Capture d’écran 2023-06-13 à 10 43 07" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/52194475/edadee6e-10af-4d52-a73b-665111f560cd">
<img width="1103" alt="Capture d’écran 2023-06-13 à 10 43 17" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/52194475/94acfc5f-5045-42e9-b659-4927d9681030">

It's work, please check version of plugin formula editors and formula statistics and refresh with CTRL + F5 / Command + Shift + R

**Comment by dmt0** [comment]
OK, fixed by upgrading your other plugin
"@progidev/jss-plugin-formula": "2.3.4",
Thanks @GBonnaire !
